const colors = {
  light: {
    text: '#ffffff',
    tint: '#e50914',
    background: '#141414',
    foreground: '#ffffff',
    card: '#1f1f1f',
    cardForeground: '#ffffff',
    primary: '#e50914',
    primaryForeground: '#ffffff',
    secondary: '#2a2a2a',
    secondaryForeground: '#cccccc',
    muted: '#2a2a2a',
    mutedForeground: '#aaaaaa',
    accent: '#e50914',
    accentForeground: '#ffffff',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#333333',
    input: '#2a2a2a',
  },
  dark: {
    text: '#ffffff',
    tint: '#e50914',
    background: '#141414',
    foreground: '#ffffff',
    card: '#1f1f1f',
    cardForeground: '#ffffff',
    primary: '#e50914',
    primaryForeground: '#ffffff',
    secondary: '#2a2a2a',
    secondaryForeground: '#cccccc',
    muted: '#2a2a2a',
    mutedForeground: '#aaaaaa',
    accent: '#e50914',
    accentForeground: '#ffffff',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#333333',
    input: '#2a2a2a',
  },
  radius: 8,
};

export default colors;
